image:
  file: .gitpod.dockerfile
ports:
- port: 5050
  onOpen: ignore
  visibility: public
tasks:
  - before: |
      rm -rf /workspace/dotfiles
      git clone https://github.com/zpthree/gitpod-dotfiles.git /workspace/dotfiles
      sh /workspace/dotfiles/base.sh
      cp $GITPOD_REPO_ROOT/.env.example $GITPOD_REPO_ROOT/.env
      node /workspace/dotfiles/php/variables.js
      npm install
      zsh
  - command: npm install -g prisma

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
